name: Package Addon

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Ship Release
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Force the deployment engine to recognize your fork as the primary slug
          CF_WOWI_G_SLUG: ClementeOcejo/angry-keystones
