name: Package Addon

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Ship Release
        uses: BigWigsMods/packager@v2
        with:
          # Explicitly tell the script that YOUR fork is the destination slug
          slug: ClementeOcejo/angry-keystones
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
